document.getElementById("card").addEventListener("click",function(){
    window.open('./ceilingIndividual.html',"_self");
})
document.getElementById("card1").addEventListener("click",function(){
    window.open('./ceilingIndividual.html',"_self");
})
document.getElementById("card2").addEventListener("click",function(){
    window.open('./ceilingIndividual.html',"_self");
})
document.getElementById("card3").addEventListener("click",function(){
    window.open('./ceilingIndividual.html',"_self");
})
document.getElementById("card4").addEventListener("click",function(){
    window.open('./ceilingIndividual.html',"_self");
})